import type { Authorizer } from '@/ports/authorizer';
import type { Cache } from '@/ports/cache';
import type { Clock } from '@/ports/clock';
import type { CommandIdempotencyStore } from '@/ports/command-idempotency-store';
import type { EventPublisher } from '@/ports/event-publisher';
import type { EventStore } from '@/ports/event-store';
import type { HealthReporter } from '@/ports/health';
import type { IdGenerator } from '@/ports/id-generator';
import type { IntegrationAttemptRepository } from '@/ports/integration-attempt-repository';
import type { Logger } from '@/ports/logger';
import type { MetricsRecorder } from '@/ports/metrics';
import type { MigrationStateRepository } from '@/ports/migration-state-repository';
import type { OutboxRepository } from '@/ports/outbox-repository';
import type { DomainPackageRepository } from '@/ports/domain-package';
import type { PolicyEngine } from '@/ports/policy-engine';
import type { ProcessStore } from '@/ports/process-store';
import type { ProjectionStore } from '@/ports/projection-store';
import type { AuditEventQueryPort } from '@/ports/audit-event-query';
import type { ResourceAvailabilityPort } from '@/ports/resource-availability';
import type { ResourceRepository } from '@/ports/resource-repository';
import type { ResourceReservationPort } from '@/ports/resource-reservation';
import type { SyncStateRepository } from '@/ports/sync-state-repository';
import type { UnitOfWorkManager } from '@/ports/unit-of-work-manager';
import type { Tracer } from '@/ports/tracer';
import type { WorkItemQueryPort } from '@/ports/work-item-query';
import type { WorkItemRepository } from '@/ports/work-item-repository';
import type { WorkflowRepository } from '@/ports/workflow-repository';

export type ApplicationDependencies = {
  authorizer: Authorizer;
  policyEngine: PolicyEngine;
  workItems: WorkItemRepository;
  workItemQueries: WorkItemQueryPort;
  workflows: WorkflowRepository;
  packages: DomainPackageRepository;
  events: EventStore;
  eventQueries: AuditEventQueryPort;
  outbox: OutboxRepository;
  eventPublisher: EventPublisher;
  unitOfWork: UnitOfWorkManager;
  syncStates: SyncStateRepository;
  projections: ProjectionStore;
  resources: ResourceRepository;
  resourceAvailability: ResourceAvailabilityPort;
  resourceReservations: ResourceReservationPort;
  integrations: IntegrationAttemptRepository;
  migrations: MigrationStateRepository;
  processes: ProcessStore;
  cache: Cache;
  commandIdempotency: CommandIdempotencyStore;
  health: HealthReporter;
  metrics: MetricsRecorder;
  logger: Logger;
  tracer: Tracer;
  clock: Clock;
  ids: IdGenerator;
};
